services:
  runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    volumes:
      - config:/etc/gitlab-runner
      - ${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - CI_SERVER_URL=https://gitlab.com/
      - RUNNER_NAME=Local GitLab Runner
      - DOCKER_IMAGE=gradle:alpine
      - RUNNER_EXECUTOR=docker
volumes:
  config: